# Generated by Django 5.1.7 on 2025-03-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('callback_token', models.CharField(max_length=100)),
                ('amount', models.IntegerField(help_text='Amount in øre (cents)')),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('SESSION_COMPLETED', 'Session Completed'), ('SESSION_FAILED', 'Session Failed'), ('SESSION_CANCELLED', 'Session Cancelled'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_FAILED', 'Payment Failed'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('shipping_method', models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'Pickup Point')], default='home', max_length=20)),
                ('shipping_cost', models.IntegerField(default=4900)),
                ('pickup_point_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('mobilepay', 'MobilePay'), ('card', 'Credit Card')], default='mobilepay', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(help_text='Price in øre (cents)')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fabric_type', models.CharField(blank=True, max_length=100, null=True)),
                ('body_fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('head_fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('under_arms_fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('belly_fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('has_vest', models.BooleanField(default=False)),
                ('vest_fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('face_style', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, help_text='Amount in øre (cents)', null=True)),
                ('status', models.CharField(max_length=50)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='core.order')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
